language: python

env:
  global:
    - TWINE_USERNAME=__token__
    - TWINE_PASSWORD: $PYPY_TOKEN

python:
  - "3.9"

deploy:
  provider: script
  script: scripts/release.sh
  on:
    tags: true

script:
  - python -m coverage run test/test_Suite.py
