language: python
python:
  - "3.9"

script:
  - python setup.py install

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: $PYPI_TOKEN
  distributions: "dist"
  skip_existing: true
  on:
    tags: true
