language: python

dist: jammy

env:
  global:
    - TWINE_USERNAME=__token__

python:
  - "3.9"

deploy:
  provider: script
  script: scripts/release.sh
  on:
    tags: true

script:
  - scripts/ci_test.sh
